services:
  # diett-frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - diett-apiserver

  diett-apiserver:
    build: ./server
    ports:
      - "8080:8080"

  diett-inference:
    build: ./services/inference
    environment:
      - WEBHOOK_URL=http://diett-apiserver:8080/webhook/inference_result