on:
    push:
        branches: [main]
    workflow_dispatch: # added for manual trigger, remove once fully built
jobs:
    train:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run training script in Kaggle server
              uses: Frederisk/kaggle-action@v1.0.0
              with:
                username: ${{ secrets.KAGGLE_USERNAME }}
                key: ${{ secrets.KAGGLE_KEY }}
                enable_gpu: enable
                title: train
                code_file: train/train.py
            - name: Retrieve training logs
              env:
                KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
                KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
              run: |
                mkdir -p logs
                kaggle kernels output ${KAGGLE_USERNAME}/train -p ./log
            - name: Listing the downloaded logs
              run: ls -la ./log
            - name: Publishing the model.onnx file as an artifact
              uses: actions/upload-artifact@v4
              with:
                name: trained-model
                path: ./log/model.onnx
            - name: Publishing the classes.txt file as an artifact
              uses: actions/upload-artifact@v4
              with:
                name: classes-file
                path: ./log/classes.txt
    #         - name: Moving the model.pth file to services/inference
    #           run: mv ./log/model.pth ./services/inference/model.pth
    # deploy:
    #     needs: train
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: Deploy on AWS
    #           uses: aws-actions/configure-aws-credentials@v1
    #           with:
    #               aws-access-key-id: {{ secrets.AWS_ACCESS_KEY_ID }}
    #               aws-secret-access-key: {{ secrets.AWS_SECRET_ACCESS_KEY }}
    #               aws-region: ap-south-2
