on:
    push:
        branches: [main]
    workflow_dispatch: # added for manual trigger, remove once fully built
jobs:
    train:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run training script in Kaggle server
              uses: Frederisk/kaggle-action@v1.0.0
              with:
                username: ${{ secrets.KAGGLE_USERNAME }}
                key: ${{ secrets.KAGGLE_KEY }}
                enable_gpu: enable
                title: train
                code_file: train/train.py
            - name: Retrieve training logs
              env:
                KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
                KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
              run: |
                mkdir -p logs
                kaggle kernels output ${KAGGLE_USERNAME}/train -p ./log
            - name: Listing the downloaded logs
              run: ls -la ./log
            - name: Publish the training log a release artifact
              uses: actions/upload-artifact@v4
              with:
                name: training-logs
                path: ./log/model.pth